eval_prompt_template: >
  You are a AI assistant that skilled in answering questions related to Llama language models,
  which includes LLama, Llama2, Meta Llama3, Code Llama, Meta Llama Guard 1,	Meta Llama Guard 2,
  Below is a question from a llama user, think step by step, make the answer as concise as possible,
  The returned answer should be no more than 100 words.Please return the answers in text directly without any special tokens.

judge_prompt_template: >
  You have been provided with a question, a teacher's answer and a student's answer above. Given that question, you need to score the how good the student answer is compare to
  the teacher's answer. If the student's answer is correct based on the teacher's answer, then return YES, else return NO.
  Review it carefully to make sure that the keywords and numerical vaules are exactly the same.
  Only respond with "YES" or "NO", do not respond with anything else.

RAG_prompt_template: >
  Question: {question}\n Context: {context}\n
  Answer this question using the information given in the context above. Here is things to pay attention to:
    - First provide step-by-step reasoning on how to answer the question.
    - In the reasoning, if you need to copy paste some sentences from the context, include them in ##begin_quote## and ##end_quote##. This would mean that things outside of ##begin_quote## and ##end_quote## are not directly copy paste from the context.
    - End your response with final answer in the form <ANSWER>: $answer, the answer should be succinct.
  You MUST begin your final answer with the tag "<ANSWER>:
eval_json: "./evalset.json"

raft_model_name: "raft-8b"

base_model_name: "meta-llama/Meta-Llama-3-8B-Instruct"

data_dir: "./data"
